### ISSUE TITLE
Feature request: custom http agent options

### ISSUE THREAD

**Issue by geoffdutton** [recurly/recurly-client-node#113]
Since #90, I started noticing `read ECONNRESET` popping up in our logs. We use AWS Lambda, so the lifecycle of the container can complicate things (even though the point is to simplify things ;)). I finally traced it down to the `BaseClient.js` and realized what's happening is that the recurly client object in some cases might be reused between requests, and I think the `keepAliveMsecs` might have been the culprit. Ultimately, I solved it in a really hacky way:

```
const recurlyClient = new recrlyV3.Client(
  RECURLY_API_KEY
)
delete recurlyClient._httpOptions.agent
recurlyClient._httpOptions.agent = new https.Agent({
  keepAlive: true
})
```
It's been a few weeks and the `read ECONNRESET` errors have disappeared.

There's no rush, this works all fine and dandy, but I was wondering if we could pass our own options maybe via the constructor, or at least more of a documented method to set our own https agent.

Like I said this will work fine for now, so there's no rush. Any thoughts? Can I provide you with further information?

Thanks again for all your help and quick responses!

**Comment by bhelx** [comment]
@geoffdutton Interesting. Haven't thought about this case. I'd like to do some more research about this use case. A couple initial thoughts here:

1. We will soon have more options that you can pass into the `Client` constructor. That will likely include the keepalive timeout config. I can work on that sooner if it helps.
2. Do you have any resources on how these outbound connections should be handled in a lambda-like environment? I'd like to do a little research into how we can confidently support this.
3. It might make sense to add a `close()` to the client to allow the programmer to tear down the connection when they are done. Even so, I still think keeping the connection open as long as possible will be much more performant.

**Comment by bhelx** [comment]
I'm also going to verify with the developer of that PR that we need the `keepAliveMsecs` property. Hearing that maybe we don't.

**Comment by bhelx** [comment]
Going to close this until further notice. Feel free to reopen or continue the discussion. BTW, we will have keepalive and timeout settings coming soon.
