### ISSUE TITLE
Is `nextBillDate` missing from the Subscription model?

### ISSUE THREAD

**Issue by richthegeek** [recurly/recurly-client-node#115]
The documentation for creating and retrieving a subscription mentions a `next_bill_date / nextBillDate` field but this is missing from the TS annotations.

Is it missing from the actual request also, or is automatically snake-cased and passed?

**Comment by bhelx** [comment]
We do not have the request types exposed in typescript yet. That was a follow-up that we left from the original task: https://github.com/recurly/recurly-client-node/issues/29
Right now they are just unstructured objects, but we should eventually expose those. There are cases, like this one, where the request object is different than the response.

I believe `next_bill_date` is a write-only field. You should be able to include it in the request as `nextBillDate` (we support snake cased as well but try to encourage camel), but it does not come back in the response. From the documentation:

```
If present, this sets the date the subscription's next billing period will start (current_period_ends_at). This can be used to align the subscription’s billing to a specific day of the month. The initial invoice will be prorated for the period between the subscription's activation date and the billing period end date. Subsequent periods will be based off the plan interval. For a subscription with a trial period, this will change when the trial expires.
```

You may be wanting to look at `current_period_ends_at`.

**Comment by richthegeek** [comment]
Understood, so only the response fields are included :+1:

I know this is _not_ a support channel but I'm having trouble getting an answer out of Recurly support and you seem like you'd know: is there a way to change the billing date of a subscription and have the amount pro-rated automatically? If so, what endpoint should I be looking at?

If you don't want to or can't answer outside of official channels I understand 100%

**Comment by bhelx** [comment]
> If you don't want to or can't answer outside of official channels I understand 100%

You can ask questions here anytime! The reason we have that warning is that we don't work for the support team and thus can't always get you a timely answer. Having said that, it's best to keep the topics on this repo specific to the node client if possible.

WRT your question:

> is there a way to change the billing date of a subscription and have the amount pro-rated automatically? If so, what endpoint should I be looking at?

There are 2 pathways to changing subscriptions, the `modifySubscription` call and the `createSubscriptionChange` call. `modifySubscription` is for changing attributes that do not result in a new invoice being created or have no impact on the billed amount `createSubscriptionChange` creates a `SubscriptionChange` object which will either trigger an invoice or affect the amount of a future one.

I don't see the `next_bill_date` in the change endpoint, so I'm not sure what you are asking is doable (in one call at least). Could you explain a scenario?

**Comment by bhelx** [comment]
I'm going to close this question for now but feel free to keep the conversation going.

**Comment by richthegeek** [comment]
Thanks for helping out :)

The scenario is we have customers who are monthly on the day they signed up, and we want to align them all to the 1st of each month. And of course it's not viable to do that if we're giving everyone 1-30 days unbilled time.

It's beginning to look like we need to Postpone the subscription and manually issue a charge for the prorated amount to each account.

**Comment by bhelx** [comment]
> It's beginning to look like we need to Postpone the subscription and manually issue a charge for the prorated amount to each account.

Yes I think that may work. But would it work to set the `nextBillDate` during the purchase / signup flow? There is a path in the purchase request `purchase.subscriptions[i].next_bill_date`

The docs:

```
string <date-time>  (Next bill date)  If present, this sets the date the subscription's next billing period will start (current_period_ends_at).  This can be used to align the subscription’s billing to a specific day  of the month. The initial invoice will be prorated for the period  between the subscription's activation date and the billing period end  date. Subsequent periods will be based off the plan interval. For a  subscription with a trial period, this will change when the trial expires.
```

So when someone signs up on `May 14th`, you could set next_bill_date to `June 1` during the createPurchase call

**Comment by Dania02525** [comment]
@richthegeek creating a subscription with the `next_bill_date` parameter will cause the subscription to be prorated on its first invoice, and begin billing on that date.  On the other hand, postponing the subscription after it is created using the same `next_bill_date` parameter in the put request *won't* cause any proration- but instead will just change the billing date.

**Comment by richthegeek** [comment]
@bhelx yep, we're doing it for new customers but this is for the existing customers. Think I've got it figured out now, thanks fo much for the help!

@Dania02525 :+1:
