### ISSUE TITLE
looking for fake recurly token for testing

### ISSUE THREAD

**Issue by muz3** [recurly/recurly-client-node#116]
Hi team,

I am writing my backend integration tests. I could get everything worked, except before running my test I have to use UI to get a recurly token, then plug that into my test cases. I wonder if there is a good way to automate this flow. Or is there a fake token can be used directly. simply like you can use a fake credit card number 4111-1111-1111-1111. 

thanks

**Comment by bhelx** [comment]
Thanks for the question @muz3,

This is actually a feature we are planning out but it's not ready. For the time being can implement it yourself. When you are creating the BillingInfo object on your server, just switch out the token info for a test credit card. Something like this:

```javascript
// assume you have created purchaseReq from your frontend data https://developers.recurly.com/api/v2019-10-10/index.html#operation/create_purchase
// lets assume your web request data is in `params`

if (params['recurly-token'] === "test-good-card") {
  purchaseReq.account.billing_info = {
    firstName: 'John',
    lastName: 'Smith',
    number: '4111-1111-1111-1111',
    month: '12',
    year: '2025',
    cvv: '123',
   // other details you might need
  }
} else {
  purchaseReq.account.billing_info = { token_id: params['recurly-token'] }
}
// continue on with your request
```

You could add a few tokens-to-card mappings for different scenarios: https://docs.recurly.com/docs/test

**Comment by muz3** [comment]
@bhelx , thanks a lots. forcing the billing address update from the server-side works great for my tests.

**Comment by bhelx** [comment]
@muz3 great! Let us know if you have any other questions. We'll try to post back here when the we roll out our own test token support.

**Comment by muz3** [comment]
@bhelx ,  that's great. What is the best community channel for Recurly, twitter, slack or something else? I would like to keep up with any development related news.

**Comment by bhelx** [comment]
We don't have a specific channel for developer announcements. Best place to find them is in [release notes](https://github.com/recurly/recurly-client-node/releases), [changelogs](https://github.com/recurly/recurly-client-node/blob/master/CHANGELOG.md), or our [blog](https://blog.recurly.com/)

**Comment by j10sanders** [comment]
Hard to go through all the release notes since May.  Was a mock-token ever implemented?

**Comment by MangoChris** [comment]
+1 It would be very useful to be able to mock the token, the idea of not having realistic integration tests for something as important as billing doesn't appeal to me.

**Comment by noctivityinc** [comment]
+1 any update here?  JS code doesnt do us any good when we are writing backend Ruby rspec request specs.
