### ISSUE TITLE
Error types

### ISSUE THREAD

**Issue by SKaistrenko** [recurly/recurly-client-node#150]
Seems like `recurly.errors.*` are not available in TS?

**Comment by SKaistrenko** [comment]
@bhelx is that something you're able to confirm?

**Comment by douglasmiller** [comment]
@SKaistrenko, thank you for the question. We are looking into this and will provide you with an update shortly.

**Comment by dbrudner** [comment]
@SKaistrenko Yup, it looks the type is missing. We'll be looking to add it as soon as we can. Thanks for opening the issue! We'll report on progress inside this thread.

**Comment by SKaistrenko** [comment]
Thank you!

**Comment by SKaistrenko** [comment]
@douglasmiller we need to re-open. I'm getting error on trying to use this
```
TypeError: Right-hand side of 'instanceof' is not an object
    at RecurlyService.<anonymous> (...)
    at Generator.throw (<anonymous>)
    at rejected (...)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
on `if (e instanceof NotFoundError) {`

Logged error: 
```
NotFoundError [RecurlyNotFoundError]: Couldn't find Account with code = code
    at Client._errorFromResponse (.../node_modules/recurly/lib/recurly/BaseClient.js:163:19)
    at .../node_modules/recurly/lib/recurly/BaseClient.js:96:28
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  type: 'not_found',
  params: [ { param: 'account_id' } ]
}
```

**Comment by SKaistrenko** [comment]
@douglasmiller we need to re-open. I'm getting error on trying to use this
```
TypeError: Right-hand side of 'instanceof' is not an object
    at RecurlyService.<anonymous> (...)
    at Generator.throw (<anonymous>)
    at rejected (...)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
on `if (e instanceof NotFoundError) {`

Logged error: 
```
NotFoundError [RecurlyNotFoundError]: Couldn't find Account with code = code
    at Client._errorFromResponse (./node_modules/recurly/lib/recurly/BaseClient.js:163:19)
    at /Users/serhiikaistrenko/code/pws/node_modules/recurly/lib/recurly/BaseClient.js:96:28
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  type: 'not_found',
  params: [ { param: 'account_id' } ]
}
```

**Comment by douglasmiller** [comment]
Oh no, we're sorry about that. I'll reopen and we'll take a look. Thanks for letting us know!

**Comment by douglasmiller** [comment]
@SKaistrenko I'm a little confused by the error that you're having. Could you provide a runnable code sample?

Looking at the nodejs example for the [get_account](https://developers.recurly.com/api/v2019-10-10/index.html#operation/get_account) operation, the catch block is checking `err instanceof recurly.errors.NotFoundError`.  I'm assuming that you've imported the error class itself, but a runnable code sample would help us out in debugging the issue.

**Comment by SKaistrenko** [comment]
Ok, so in your types definitions file `recurly.d.ts` you're exporting each error individually (e.g. `export class ResponseError extends ApiError { }`) while in your actual `recurly.js` you're only exporting error as `exps.errors = require('./recurly/api_errors')`. That causes problems because types don't match actual code. Individual errors shouldn't be exported in types definitions. Same goes for `export interface ErrorMap` - it's not exported as a standalone module in `recurly.js`

Reproduction repo: https://github.com/SKaistrenko/recurly-reporduce-error-issue

**Comment by SKaistrenko** [comment]
@douglasmiller ^^^

**Comment by SKaistrenko** [comment]
Doing `errors.ClientError` doesn't work either

**Comment by douglasmiller** [comment]
@SKaistrenko I believe that https://github.com/recurly/recurly-client-node/pull/160 should fix this.

**Comment by SKaistrenko** [comment]
Hope so
