### ISSUE TITLE
Generate unique coupon codes not available

### ISSUE THREAD

**Issue by SKaistrenko** [recurly/recurly-client-node#152]
https://developers.recurly.com/api/v2019-10-10/index.html#operation/generate_unique_coupon_codes doesn't seem to be available in this package. Could you confirm?

**Comment by SKaistrenko** [comment]
If that is something that I should submit a PR for, let me know

**Comment by douglasmiller** [comment]
@SKaistrenko you're correct that the `generate_unique_coupon_codes` operation is not present in the client libraries. This is something that we have wrestled with and are trying to find a good solution for. 

The backend process that generates unique codes is asynchronous and the response currently only contains a `Location` header. We will talk about options internally about how to best address this gap. I'll leave this issue open for now until we can provide an update.

**Comment by SKaistrenko** [comment]
So this is more than just submitting POST request to `https://v3.recurly.com/sites/{site_id}/coupons/{coupon_id}/generate`?

**Comment by douglasmiller** [comment]
@SKaistrenko the endpoint is functional and you can manually generate the POST request. The only issue is that the client's do not provide the capability to perform the request. I'm looking through the reasoning behind the intentional omission and will provide an update shortly.

**Comment by SKaistrenko** [comment]
Gotcha, thanks!

**Comment by douglasmiller** [comment]
@SKaistrenko, it looks like there are still some complications with including the `generate_unique_coupon_codes` operation in the client. From my research, it may be possible to include support in a limited fashion though. 

I've created a feature request for this and will keep this issue open to provide updates to you.

**Comment by SKaistrenko** [comment]
Ok, thanks! Keep me posted.

**Comment by SKaistrenko** [comment]
@douglasmiller do you guys have any updated on that?

**Comment by douglasmiller** [comment]
@SKaistrenko I've added this to our backlog. We will update this when we have more information.

**Comment by douglasmiller** [comment]
@SKaistrenko I realize that it's been quite some time, but it is now possible to generate unique coupon codes using the `4.x` version of the client. Please let us know if that doesn't work for you.

**Comment by SKaistrenko** [comment]
Thank you for taking care of that!
