### ISSUE TITLE
Pager.eachPage type is incorrect

### ISSUE THREAD

**Issue by SKaistrenko** [recurly/recurly-client-node#157]
**Describe the bug**

Current typing is `eachPage(): AsyncIterable<T>;`, expected: `eachPage(): AsyncIterable<T[]>;`

**To Reproduce**

Check types

**Expected behavior**

N/a

**Your Environment**

- Which version of this library are you using? 3.15.0
- Which version of the language are you using? Node 12

**Comment by SKaistrenko** [comment]
@douglasmiller any updates on this

**Comment by douglasmiller** [comment]
@SKaistrenko we are looking into getting the fix for this included in the next client release, which should be today or tomorrow

**Comment by SKaistrenko** [comment]
Awesome, thanks!

**Comment by SKaistrenko** [comment]
I see it working as expected, thanks!
