### ISSUE TITLE
Allow optional "host" and "port" config parameters

### ISSUE THREAD

**Issue by markovaljaots** [recurly/recurly-client-node#186]
Currently `host` and `port` are hardcoded in BaseClient.js and it makes it difficult to create functional tests using [MockServer](https://www.mock-server.com/) for instance.

It would be great if `host` and `port` would be optional config parameters and if these are not specified, host and port would default to `v3.recurly.com:443`.

I can create a PR, but wanted to first ask for your input as well.

**Comment by douglasmiller** [comment]
Hey @markovaljaots, 

We don't officially support changing the host and port configuration of the client, however it is possible.

```node
var client = new recurly.Client(apiKey)
client._httpOptions.host = 'custom host'
client._httpOptions.port = 'custom port'
```

I apologize for the unreasonably long response time to this issue. It fell off of our radar.
