### ISSUE TITLE
Bad cast when building request

### ISSUE THREAD

**Issue by romeroadrian** [recurly/recurly-client-node#19]
There is an issue in the castRequest function (https://github.com/recurly/recurly-client-node/blob/3_0_0_beta/lib/recurly/Caster.js#L30) when used with a payload that includes an array of strings (needed for coupon codes).

I think the problem itself is here https://github.com/recurly/recurly-client-node/blob/3_0_0_beta/lib/recurly/Caster.js#L37. 
First branch of the if is skipped as `value[0]` is not an object. 
The second branch is executed since `typeof value === 'object'` is true when value is an array. This causes a recursion over the same function, and the array ends up being casted as an object with array indices as keys.

The issue can be reproduced using something like the following:

```
{
  "currency": "USD",
  "account": {
    "code": "account code"
  },
  "subscriptions": [{
    "planCode": "plan code"
  }],
  "couponCodes": ["coupon code"]
}
```
The casted payload is the following, notice the coupon codes being transformed into an object with indices as keys:

```
{
  "currency": "USD",
  "account": {
    "code": "account code"
  },
  "subscriptions": [{
    "plan_code": "plan code"
  }],
  "coupon_codes": {
    "0": "coupon code"
  }
}
```

**Comment by bhelx** [comment]
@romeroadrian Thanks so much for the level of detail of this issue. I was able to immediately write a case to reproduce. I've created a patch in PR #20 . I also wrote in some extra text cases while I was there. I verified that the request is now working by testing the `createPurchase` operation. Please have a look and let me know what you think. I have a few other commits queued up so we can release this after it's merged.

**Comment by bhelx** [comment]
Closed with #20

**Comment by romeroadrian** [comment]
Thanks @bhelx !

Would it be possible to port this fix into v3-v2018-10-04 ? We are using that api version

**Comment by bhelx** [comment]
@romeroadrian No problem. With our new system, as long as the changes don't affect the interface exposed to the programmer, upstreaming fixes is easy. I'll try to keep all the versioned branches up to date with as many fixes as possible.
