### ISSUE TITLE
generateUniqueCouponCodes response throw error

### ISSUE THREAD

**Issue by kalyanattota** [recurly/recurly-client-node#227]
**Describe the bug**

` generateUniqueCouponCodes` method response throws exception due to `castJsonResponse`  in `caster.js`  as it is checking for property `object`  in the response body which is neither in  API [documentation](https://developers.recurly.com/api/v2021-02-25/index.html#:~:text=%7B-,%22limit%22%3A%200%2C,-%22order%22%3A%20%22string%22%2C)  nor in the response class `UniqueCouponCodeParams` .

**To Reproduce**

Steps to reproduce the behavior.

Call `generateUniqueCouponCodes` with `coupon_id` and `couponBulkCreate` .

Response would throw error as below.                 

`  TypeError: Cannot read property 'replace' of undefined
    at Object.className (/lib/recurly/utils.js:3:6)
    at Object.castJsonResponse (lib/recurly/Caster.js:37:18)
    at /lib/recurly/BaseClient.js:100:34 `

**Expected behavior** Response should be success.

- Which version of this library are you using? 4.10.0

**Comment by douglasmiller** [comment]
@kalyanattota, thank you for bringing this to our attention. You're absolutely right that the response needs to contain an `object` key for the client to cast to an appropriate resource.

We will get this fixed on the API side as soon as possible. I'll leave this issue open until the fix gets deployed.

**Comment by kalyanattota** [comment]
@douglasmiller  thanks for the quick update. Is it possible to provide an ETA for this fix pls? Thanks.

**Comment by douglasmiller** [comment]
Unfortunately, I cannot provide any time estimate beyond saying that we are in a code freeze until the end of the year. 

If it is of any help, the unique coupon codes will still be generated asynchronously. The API response is limited to providing query parameters for the `list_unique_coupon_codes` operation: https://developers.recurly.com/api/v2021-02-25/index.html#operation/list_unique_coupon_codes

**Comment by douglasmiller** [comment]
@kalyanattota The fix for this was recently deployed to the production environment. Please let us know if you have any other questions or issues.
