### ISSUE TITLE
No overloaded constructor for Client config

### ISSUE THREAD

**Issue by alko89** [recurly/recurly-client-node#246]
The type definition for Client constructor doesn't include the overloaded method to include client options. Because of that I'm unable to define a region as described in documentation:

![image](https://user-images.githubusercontent.com/2822030/157846166-7ca8da01-5417-412e-8081-e2c85ece15c4.png)

Ignoring types does work so its obvious its a type issue:

![image](https://user-images.githubusercontent.com/2822030/157846268-49531728-cffb-413e-80ff-02d9cf6936bf.png)

Related to #177

**Comment by douglasmiller** [comment]
Hey @Alko89,

Thank you for bringing this to our attention. The region support was only recently added and the typescript definitions were missed. We will have to update our code generator to fix this.

I'll leave this issue open until the fix has been merged and deployed.

**Comment by alko89** [comment]
Noticed the PR, tested working. Thanks for the quick fix!

On an unrelated note some typings do leave a lot to be desired. I noticed a lot of parameters have Object type instead of an actual type.
