### ISSUE TITLE
configure subdomain

### ISSUE THREAD

**Issue by rafid-kore** [recurly/recurly-client-node#254]
How can I configure my **subdomain** in this library ? if my recurly site is https://test1.recurly.com how can I configure test1 in this library ? I have seen setting apikey would be like this _**const client = new recurly.Client(myApiKey)**_

**Comment by douglasmiller** [comment]
Hey @rafid-kore, there is no need to specify your subdomain when using the client. Your private API key is all that is necessary to use the client.

**Comment by rafid-kore** [comment]
When I used this code 
![image](https://user-images.githubusercontent.com/46916980/164369633-e8084d6a-5a06-44b5-aec3-004d71b8bb28.png)
getting this error 
![image](https://user-images.githubusercontent.com/46916980/164369669-c6c47e18-cc15-42cd-b946-7c005dee4869.png)
