### ISSUE TITLE
Cannot report usage saying "Couldn't find AddOn"

### ISSUE THREAD

**Issue by sunshineo** [recurly/recurly-client-node#266]
Using latest 4.20.0
```Javascript
    const subscriptionId = 'r381e55u0r7x'
    const addOnId = 'qn7dfe37vr2h'
    try {
        await client.createUsage(subscriptionId, addOnId, {
            amount: 1,
            recordingTimestamp: new Date()
        })
    }
    catch(e) {
        console.log(e)
    }
```

Output
```bash
NotFoundError [RecurlyNotFoundError]: Couldn't find AddOn with add_on id = qn7dfe37vr2h
    at Client._errorFromResponse (/Users/gordon/workspace/pipe17/scripts/2022-08-02-view-recurly-data/node_modules/recurly/lib/recurly/BaseClient.js:190:19)
    at /Users/gordon/workspace/pipe17/scripts/2022-08-02-view-recurly-data/node_modules/recurly/lib/recurly/BaseClient.js:106:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'not_found',
  params: []
}
```

The addon is right there
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1072766/184003845-f4f36f9f-0982-42f2-a1cd-81862a4bdbda.png">
The subscription is for that plan of course

**Comment by sunshineo** [comment]
Actually reporting the usage through api does not work either
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1072766/184005999-bd51cb8f-cd21-4dd2-90c5-1e5731b62a14.png">

**Comment by sunshineo** [comment]
Actually we found the bug on our side.

**Comment by douglasmiller** [comment]
Good to hear that you were able to figure out the issue, @sunshineo. 

Please don't hesitate to reach out with any other issues.
