### ISSUE TITLE
Typescript types

### ISSUE THREAD

**Issue by wcauchois** [recurly/recurly-client-node#29]
Hi,

I wanted to just chime in that typescript support would be much appreciated, especially if the types were baked into the library itself.

Thanks!

**Comment by bhelx** [comment]
Thanks for the recommendation @wcauchois. I admit I have no experience with typescript so I cannot promise a timeframe, but since we utilize code generation in this client, I actually think this can be achieved and maintained without much effort. I am also aware that it will be extremely valuable to our typescript users and is worth doing.

I'm going to open a backlog ticket for myself to take this on. I may not get to it before we release (Oct 1), but should soon after.

**Comment by Kriskit** [comment]
Has there been progress on this? I will soon implementing Recurly into a platform written in Typescript and would prefer not to have to write my own declarations but will if it's still a way off.

**Comment by bhelx** [comment]
@Kriskit I'll look into a level of effort on this today. There seems to be quite a bit of interest so I'm pretty confident we will start to provide it.

Personally, I'd recommend not doing it yourself because it would be tough to maintain, it's a huge surface area and the API is slightly changing constantly. We utilize generation from an OpenAPI schema in this library so we can generate these files and keep them up to date.

I'll get back to y'all with some kind of date today.

**Comment by bhelx** [comment]
@wcauchois @Kriskit Consulted with another developer on our team with typescript experience. I'm going to generate the definition file and we'll try to publish test next week. I'll try to have this in the mainline release by the end of the month.

**Comment by Kriskit** [comment]
That's great, thanks for responding so quickly.

**Comment by bhelx** [comment]
Got a work in progress PR going: https://github.com/recurly/recurly-client-node/pull/48
we'll test and refine next week

**Comment by bhelx** [comment]
@wcauchois @Kriskit Would y'all mind trying out #48? We've loosely tested it and it seems to be working.

Our test project is 2 files:

### package.json

```json
{
	"name": "recurly-ts-test",
	"version": "1.0.0",
	"description": "",
	"main": "index.js",
	"scripts": {
		"start": "tsc ./index.ts && node ./index.js"
	},
	"keywords": [],
	"author": "",
	"license": "ISC",
	"dependencies": {
		"recurly": "github:recurly/recurly-client-node#typescript-definitions-file"
	},
	"devDependencies": {
		"@types/node": "^12.11.1",
		"typescript": "^3.6.4"
	}
}
```

### index.ts

```ts
import * as recurly from "recurly";

const client = new recurly.Client('<insertapikey>')

async function runIt() {
  //const accounts = client.listAccounts({
  //  beginTime: '2018-12-01T00:00:00Z',
  //  sort: 'updated_at'
   // })
  // for await (const acct of accounts.each()) {
  //   console.log(acct.id)
  // }

  const acctReq = {
    code: 'new-account-code',
    firstName: 'Benjamin',
    lastName: 'Du Monde'
  }
  let account = await client.createAccount(acctReq)
  console.log(account)
  account = await client.getAccount(account.id)
  console.log(account)
}

runIt()
```

To run:

`npm start`

One thing I'm having trouble with understanding is how to write the definitions for the AsyncIterator part of the Pager class. Seeing the following error below when trying to use the await-of syntax:

<img width="837" alt="Screen Shot 2019-10-18 at 1 32 01 PM" src="https://user-images.githubusercontent.com/185919/67119544-02caeb80-f1ad-11e9-9fc5-c9ce09763d2e.png">

I'll do some more research, let me know if you have any ideas.

**Comment by wcauchois** [comment]
@bhelx regarding the async iterator thing, maybe you want AsyncIterable instead? looking at Pager i think that is what you're returning https://github.com/recurly/recurly-client-node/blob/adcfbaf551f12c797d922f8a02e28959d8a6a0e7/lib/recurly/Pager.js#L30

![image](https://user-images.githubusercontent.com/300544/67131455-bb575600-f1d2-11e9-8231-28d5938c53c1.png)

**Comment by bhelx** [comment]
@wcauchois seems like you were right! Pushed a new commit and all seems to be working. https://github.com/recurly/recurly-client-node/pull/48/commits/9275552f781bb8da5a2a5555c09af7cf22546838

Here is a test script. Mind giving the commit a look?

```ts
import * as recurly from "recurly";

const client = new recurly.Client('0ee0db0faa9640849ee495d48fb3274d')

async function runIt() {
  const accounts = client.listAccounts({
    beginTime: '2018-12-01T00:00:00Z',
    sort: 'updated_at',
    limit: 200
    })
  for await (const acct of accounts.each()) {
    console.log(acct.id)
  }

  const acctReq = {
    code: 'test12345',
    firstName: 'Benjamin',
    lastName: 'Du Monde'
  }
  let account = await client.createAccount(acctReq)
  console.log(account)
  account = await client.getAccount(account.id)
  console.log(account)
  account = await client.updateAccount(account.id, { firstName: "Bill", lastName: "Cauchois" })
  console.log(account)
  account = await client.deactivateAccount(account.id)
  console.log(account)
}

runIt()
```

**Comment by bhelx** [comment]
We'll give it the weekend and give @Kriskit a chance to chime in. Once I get the okay from you @wcauchois I'll document it and get a patch out (hopefully Monday).

**Comment by bhelx** [comment]
@wcauchois @Kriskit Any final thoughts?

**Comment by wcauchois** [comment]
left a few comments. i really appreciate your work!

**Comment by Kriskit** [comment]
@bhelx It's a good start, I'm not sure if this to do with your code generation or what but my only concern is the nondescript `object` parameters everywhere, looking at the client jsdoc comments there are clearly defined parameters that could be turned into interface definitions for example:

```TypeScript
interface ListAccountsParameters {
       ids?: string[];
       limit?: number;
       order?: 'asc' | 'desc';
       sort?: keyof Account; // I'm unsure if the camelcase sorts get translated to snake case?
       beginTime?: Date;
       endTime?: Date;
       email?: string;
       subscriber?: boolean;
       pastDue?: string; // Should this not be a boolean?
}
```

I also notice the use of returning `Promise<Empty>`, do these actually return an empty object or are they `void`? If the latter then `Promise<void>` will suffice.

Hope this is of some use. I'm going to be starting on my integration with Recurly soon so I'll have more input potentially as I go forward.

**Comment by bhelx** [comment]
Just so y'all know, this got bundled into the `3.3.0` release: https://github.com/recurly/recurly-client-node/blob/master/CHANGELOG.md#330-2019-12-19

Keep an eye out for the next steps as outlined in the [PR](https://github.com/recurly/recurly-client-node/pull/48).

**Comment by bhelx** [comment]
Request types will be coming in version `4.0.0`: https://github.com/recurly/recurly-client-node/pull/134/

**Comment by bhelx** [comment]
@wcauchois @Kriskit Perhaps y'all have some opinions on #134
