### ISSUE TITLE
3.0.0-beta.4 is not available

### ISSUE THREAD

**Issue by rafdizzle86** [recurly/recurly-client-node#30]
In the readme it says to use `3.0.0-beta.4` but it looks like it doesn't exist in the npm registry:

```
$ npm install recurly@3.0.0-beta.4 --save-prod
npm ERR! code ETARGET
npm ERR! notarget No matching version found for recurly@3.0.0-beta.4
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

When I run `yarn install` on the other hand, it asks me to select which version of recurly I want to install and it looks like it only goes up to `3.0.0-beta.3`:
```
Couldn't find any versions for "recurly" that matches "3.0.0-beta.4"
? Please choose a version of "recurly" from this list: (Use arrow keys)
❯ 3.0.0-beta.3 
  3.0.0-beta.2 
  3.0.0-beta.1 
  0.0.0 
```

Was the `.4` version of the beta not released yet maybe?

**Comment by rafdizzle86** [comment]
For reference the `3.0.0-beta.4` is referenced in the readme here:

https://github.com/recurly/recurly-client-node/blame/3_0_0_beta/README.md#L25

Also, it looks like in the "releases" tab in GH, `3.0.0-beta.4` is not listed.

**Comment by bhelx** [comment]
Hey stranger!

I fixed the README. beta.3 is in fact the latest: https://github.com/recurly/recurly-client-node/releases/tag/3.0.0-beta.3

We may release a beta.4, but will likely wait for 3.0.0 on October 1st.
