### ISSUE TITLE
add_ons.add_on is invalid (for create_subscription_change)

### ISSUE THREAD

**Issue by 0xterran** [recurly/recurly-client-node#314]
**Describe the bug**

Cannot include add_ons on operation [create_subscription_change](https://recurly.com/developers/api/v2021-02-25/#operation/create_subscription_change). Validation fails and docs do not provide info on this issue. Recurly servers return the following errors:

```
{
  type: 'validation',
  message: 'Add-ons add on is invalid',
  params: [ { param: 'add_ons.add_on', message: 'is invalid' } ]
}
Request failed with status code 422
```

the docs say nothing about this `add_ons.add_on` field and the error message doesnt elaborate. when i attempt to include this field, it will reject with a different error:

```
{
  type: 'validation',
  message: 'Please remove the following unpermitted parameters from your request: add_on.',
  params: [ { param: 'add_on' } ]
}
Request failed with status code 400
```

**To Reproduce**

```ts
const payload = {
    timeframe: "now",
    add_ons: [
      {
        code: planAddOnCode,
        unit_amount: 1509,
        // add_on: "hello", // try with & without this
      },
    ],
  };

  try {
    const token = await getRecurlySecret();
    const response = await axios.post(
      `https://v3.recurly.com/subscriptions/${subscriptionID}/change`,
      payload,
      {
        headers: {
          "Content-Type": "application/json",
          Accept: "application/vnd.recurly.v2021-02-25",
          Authorization: `Basic ${btoa(token)}`,
        },
      }
    );
  } catch (e: any) {
    console.log(e.response.data.error);
    console.log(e.message);
  }
```

**Expected behavior**

I expected to be able to add a planAddOn to an existing subscription.

**Your Environment**

- Which version of this library are you using?
Tested with nodejs sdk as well as REST calls

- Which version of the language are you using?
node v18, but also tried with REST calls

**Comment by 0xterran** [comment]
This person seems to be having the same issue:
https://stackoverflow.com/questions/74388610/recurly-adding-addon-to-subscription-error

**Comment by 0xterran** [comment]
@bhelx @douglasmiller hi just a polite follow-up 🙏 this is a blocker for me

**Comment by douglasmiller** [comment]
Hi @0xterran,

The Plan must be configured to allow the AddOn that you are including in your subscription change request. Could you confirm that the value of `planAddOnCode` is valid for the Subscription's Plan?

I agree that the error message is rather confusing and will see if we can have some clarification added there.

**Comment by 0xterran** [comment]
Hi @douglasmiller, are you referring to this? (expand image) I see this checkbox in the plan settings `/plans/{planId}/edit`. I have set the checkbox option to `true`. I still seem to seeing the same issue though.

<details>


<img width="875" alt="Plans_-_Recurly" src="https://github.com/recurly/recurly-client-node/assets/96885027/205308b0-7024-4c8c-9310-1dc1a507676d">

<img width="625" alt="Screenshot 2023-08-03 at 7 44 33" src="https://github.com/recurly/recurly-client-node/assets/96885027/dfab1f7e-c464-422f-960e-cd8bb4337fd8">

</details>

I also tried making a new plan+addon+subcription+subaddon (using `allow_any_item_on_subscriptions=true` on `POST /plans`). Still seeing the same issue.



> Could you confirm that the value of planAddOnCode is valid for the Subscription's Plan?

What do you mean by this? I can confirm that `planAddOnCode` is from the same plan that the subscription was created from. And that `plan. allow_any_item_on_subscriptions = true` now

**Comment by 0xterran** [comment]
Hi @douglasmiller just a polite follow up on this. Sorry for the bother 🙏

**Comment by douglasmiller** [comment]
@0xterran, I didn't realize that you were referring to an Item based AddOn. In that case, you need to include `add_on_source: "item"` in the AddOn object. The value defaults to `plan_add_on`, which is the source of the error message that you are seeing.


```diff
const payload = {
  timeframe: "now",
  add_ons: [
    {
      code: planAddOnCode,
+     add_on_source: "item",
      unit_amount: 1509,
      // add_on: "hello", // try with & without this
    },
  ],
};
```

**Comment by douglasmiller** [comment]
@0xterran, I hope that my last comment helped solve your issue. I'm going to close this issue, but feel free to re-open if you have additional questions about this topic.
