### ISSUE TITLE
Without the siteId param, I am getting an error

### ISSUE THREAD

**Issue by rafdizzle86** [recurly/recurly-client-node#37]
When I initialize the client without the siteId param (as instructed by the README), I am getting the following error:

```
client.getSite()
Promise {
  <rejected> TypeError: Cannot read property 'toString' of undefined
    at Object.keys.forEach.name (/Users/rafi/cloudbees-repos/rollout/api.rollout.io/node_modules/recurly/lib/recurly/BaseClient.js:38:76)
...
```

Am I initializing it wrong? After looking at the `BaseClient` I think it is expecting a `siteId` param to be passed to the `Client()` function:

```
  _interpolatePath (path, parameters = {}) {
    parameters['site_id'] = this.siteId
    Object.keys(parameters).forEach(name => {
      path = path.replace(`{${name}}`, encodeURIComponent(parameters[name].toString()))
    })
    return path
  }
```

**Comment by rafdizzle86** [comment]
Also - when I _do_ put in the site id (e.g. subdomain), then it is returning the following error when I call `getSite()`:

```
(node:11540) UnhandledPromiseRejectionWarning: RecurlyNotFoundError: Couldn't find Site with id = rollout-sandbox
```

In the previous version of the client, I think the passing in the subdomain worked- has that changed?

**Comment by bhelx** [comment]
Furthermore, remember that using the subdomain requires the friendly version of the site-id. so your site-id should be `subdomain-rollout-sandbox`. See my comment on your other issue: https://github.com/recurly/recurly-client-node/issues/38#issuecomment-537094979

**Comment by bhelx** [comment]
assuming you are on beta.4, you might want to try [beta.5](https://github.com/recurly/recurly-client-node/releases/tag/3.0.0-beta.5)

**Comment by bhelx** [comment]
Just to be extra clear, getSite takes the site-id:

```js
let site = await client.getSite("subdomain-rollout-sandbox")
```

**Comment by rafdizzle86** [comment]
I didn't realize beta 5 was out, that resolved the issue, thanks!
