### ISSUE TITLE
Guidance on testing

### ISSUE THREAD

**Issue by rafdizzle86** [recurly/recurly-client-node#46]
What are best practices for mocking and stubbing the recurly client?

I'm using a combination of `chai.js`, `mocha.js` and `sinon.js` for testing. I'm using `sinon.js` to stub the recurly client so I can return my own stubbed objects- however when I look at what the actual client returns I see there are a lot of instantiated resource objects that are dynamically created. 

For example the response from `getBillingInfo` is a a variety of resource objects like `BillingInfo`, `Address`, `PaymentMethod` and `BillingInfoUpdatedBy` objects

My question is: should I try to mimic these objects on my own via fixtures?

Or should I use a package like `nock` to hijack HTTP request and try and emulate recurly's v3 json responses?

Thanks!

**Comment by rafdizzle86** [comment]
Or maybe there is another way of doing it that I have not thought about!

**Comment by bhelx** [comment]
BTW, in regards to your question here:

> For example the response from getBillingInfo is a a variety of resource objects like BillingInfo, Address, PaymentMethod and BillingInfoUpdatedBy objects

If you use the `cast` function on any resource, it will recursively cast the whole object (and it's attributes). Example:

```js
let billingInfoObj = JSON.parse(fs.readFileSync('./test/fixtures/billing_info/code-verena.json'))
let billingInfo = recurly.BillingInfo.cast(billingInfoObj)
```

The classes are aware of their schema and able to do this casting accurately.

**Comment by rafdizzle86** [comment]
That helps, thanks again @bhelx!
