### ISSUE TITLE
Cannot find module '../../package' from 'BaseClient.js'

### ISSUE THREAD

**Issue by andreasasprou** [recurly/recurly-client-node#49]
**Describe the bug**

Unable to create a new instance of the Recurly Client.

When I attempt to instantiate the client:

```javascript
import recurly from 'recurly';

const client = new recurly.Client(apiKey);
```

I get the following error

```
Cannot find module '../../package' from 'BaseClient.js'

However, Jest was able to find:
   '../../package.json'

You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['ts', 'tsx', 'js', 'jsx', 'html', '.json'].
```

**To Reproduce**

```javascript
import recurly from 'recurly';

const client = new recurly.Client(apiKey);
```

**Expected behavior**

To be able to instansiate the client and run functions exposed by it's api, e.g.

```javascript
(async () => {
  import recurly from 'recurly';

  const client = new recurly.Client(apiKey);
  await client.getSite('my-site');
})()
```

**Your Environment**

- Which version of this library are you using? 3.0.0
- Which version of ruby(*nodejs) are you using? v12.11.1

**Suggested steps to fix**

After changing line 4 in `BaseClient.js` from

```javascript
const pkg = require('../../package')
```

to

```javascript
const pkg = require('../../package.json')
```

The issue is resolved.

**Comment by bhelx** [comment]
Thanks @andreasasprou 

Let me see if I can reproduce. Looks like we'll also need to add node 12 to the TravisCI versions.

**Comment by bhelx** [comment]
@andreasasprou I could not repro but changing it causes no harm and it appears to be the suggested way to do it (using file extension).

**Comment by bhelx** [comment]
@andreasasprou When you get a moment, could you confirm `master` works for you? I'll get out a patch release.

**Comment by andreasasprou** [comment]
> @andreasasprou When you get a moment, could you confirm `master` works for you? I'll get out a patch release.

I can confirm the issue is fixed in `master`. Cheers

**Comment by bhelx** [comment]
Thanks for confirming @andreasasprou 
[3.0.1](https://github.com/recurly/recurly-client-node/releases/tag/3.0.1) is deployed with the fix.
