### ISSUE TITLE
Missing in client libraries list

### ISSUE THREAD

**Issue by bagbee** [recurly/recurly-client-node#53]
Please add `recurly-client-node` to client libraries list at https://dev.recurly.com/docs/client-libraries

**Comment by bhelx** [comment]
@bagbee thanks for the callout, the older `dev.recurly.com` doc site is for API V2. This node library is for API v3 which has a new documentation site: https://developers.recurly.com/

you'll find it listed (along with our other supported clients clients) here: https://developers.recurly.com/api/index.html
