### ISSUE TITLE
Does createPurchase() performs transaction synchronously?

### ISSUE THREAD

**Issue by 3Gorec** [recurly/recurly-client-node#57]
We are using new recurly v3 node SDK. `createPurchase()` call returns invoice with `chargeInvoice.state: 'paid'` or throws `TransactionError` if payment was declined. Documantation says that possible invoice states are "pending" "processing" "past_due" "paid"  and "failed". Is it possible to get invoice with "pending" or "processing" states in response of `createPurchase()`?
If yes how do you suggest to wait for transaction complete?

**Comment by bhelx** [comment]
@3Gorec Thanks for the question. 

The documentation spells out every state but they can depend on your payment method. If your customer's billing info is a credit card  or another synchronous payment method, and your `collection_method = automatic` (which is default), the invoices should always come back paid or the request will fail.

If you are using async payment methods such as ACH (bank accounts) or your `collection_method = manual`, you may see other states.

**Comment by bhelx** [comment]
@3Gorec Feel free to re-open if this hasn't answered your question.

**Comment by 3Gorec** [comment]
@bhelx Thank you for detailed answer.
