### ISSUE TITLE
When using Braintree to process PayPal, the billingInfo.paymentMethod is empty

### ISSUE THREAD

**Issue by geoffdutton** [recurly/recurly-client-node#67]
**Describe the bug**

We use Braintree to accept and process PayPal. When using the [getBillingInfo](https://recurly.github.io/recurly-client-node/#getbillinginfo-accountid) method, it returns something like:

```
{
      id: 'fmpormf949',
      accountId: 'gf44jg05909490',
      firstName: 'Bob',
      lastName: 'Johnson',
      company: null,
      address: {
        phone: '',
        street1: '',
        street2: '',
        city: '',
        region: '',
        postalCode: '',
        country: 'US'
      },
      vatNumber: null,
      valid: true,
      paymentMethod: {}, // an empty paymentMethod object
      fraud: null,
      createdAt: '2019-07-11T22:03:45.000Z',
      updatedAt: '2019-07-11T22:03:45.000Z',
      updatedBy: {
        ip: '111.111.111.111',
        country: 'US'
      }
}
```

The API itself returns:
```
        "payment_method": {
            "object": "braintree_v_zero"
        },
```

**Expected behavior**

I would expect the `paymentMethod` object not to be empty. I guess when using the Braintree version of PayPal, it doesn't provide a billing agreement id?

**Comment by bhelx** [comment]
@geoffdutton I believe the fix to this was just released 40 minutes ago: https://github.com/recurly/recurly-client-node/releases/tag/3.2.0

Would you mind trying it and letting us know if it solves your problem?

**Comment by geoffdutton** [comment]
@bhelx Ah, yes, I should be able to work with that. Thanks!

**Comment by bhelx** [comment]
@geoffdutton Great! Appreciate the call-out. Let us know if you find anything else.
