### ISSUE TITLE
Further clarification on terminateSubscription

### ISSUE THREAD

**Issue by geoffdutton** [recurly/recurly-client-node#97]
Regarding #95, I'm using 3.5.1, but I have to make the call like
```
    const res = await recurly.terminateSubscription(
      'xyzabc',
      {
        params: {
          refund: 'full'
        }
      }
    )
```
because `_makeRequest` is looking for a `params` key in the `options` arg: https://github.com/recurly/recurly-client-node/blob/master/lib/recurly/BaseClient.js#L51

I would expect to just pass and object with a `refund` key like:
```
    const res = await recurly.terminateSubscription(
      'xyzabc',
      {
        refund: 'full'
      }
    )
```
Is that the intended way it should work?

**Comment by douglasmiller** [comment]
@geoffdutton, sorry about the confusion there. I think that the `terminateSubscription` parameter should actually be named `options` instead  of `params`. Additionally, the doc comments are incorrect (which is likely the main point of confusion).

```
* @param {string} params.refund - The type of refund to perform:
```
Should actually be
```
* @param {string} params.params.refund - The type of refund to perform:
```

We will get the method parameter name and comments updated to alleviate confusion

**Comment by bhelx** [comment]
Just out of curiosity, what does the failure of this look like:

```js
    const res = await recurly.terminateSubscription(
      'xyzabc',
      {
        refund: 'full'
      }
    )
```

Does it silently fail?

Perhaps we should add some light top-level validation of the `options` argument and display a helpful error message.

**Comment by bhelx** [comment]
Okay, just confirmed it does. We're going to add that validation in a follow up. Thanks for pointing this out @geoffdutton !

**Comment by bhelx** [comment]
Docs should now correctly describe the interface: https://recurly.github.io/recurly-client-node/#clientterminatesubscription
